name: Build and Push Docker Image to Docker Hub
permissions:
  #contents: read
  #pages: write
  id-token: write
env:
    IMAGE_NAME: makremzitoun/netcore-api
  
on: workflow_dispatch
#workflow_dispatch
jobs:
  push_to_registry:
    name: push docker image to hub
    runs-on: ubuntu-latest
    steps:
      - name: check repository
        uses: actions/checkout@v4

      - name: login to docker registry
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USR}}
          password: ${{secrets.DOCKERHUB_TKN}}

      - name: build and push docker image to registry
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.run_number }}, ${{ env.IMAGE_NAME }}:latest
          file: ./Dockerfile
  
  Azure_Login:
   needs: push_to_registry
   name: log to azure 
   runs-on: ubuntu-latest
   steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          azcliversion: 2.42
          #creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'
          client-id: '${{ secrets.AZURE_CLIENT_ID }}' 
          tenant-id:  '${{ secrets.AZURE_TENANT_ID }}'
          subscription-id: '${{ secrets.AZURE_SUBSCRIPTION_ID }}'

      - name: 'Run az commands'
        run: |
          az acr list 
          #--query "[?contains(resourceGroup, 'mslearn-gh-pipelines')].loginServer" -o table
      - name: 'Create RG'
        run: |   
          az group create --name AzureRG --location eastus
      
      - name: 'Create ACR'
        run: | 
          az acr create --resource-group AzureRG --name dotnetaksdemo --sku Basic
      
      - name: 'Login to ACR'
        run: | 
          echo ${{ secrets.AZURE_CLIENT_SECRET }} | docker login dotnetaksdemo.azurecr.io -u ${{ secrets.AZURE_CLIENT_ID }} --password-stdin
#az acr login --name dotnetaksdemo      
      - name: 'Push To ACR'
        run: |
          docker build -t dotnetaksdemo.azurecr.io/netcore-api:latest .        
          docker push dotnetaksdemo.azurecr.io/netcore-api:latest
#${{ github.run_number }}
      - name: 'Confirmation'
        run: |
          az acr repository list --name dotnetaksdemo --output table
      - name: 'check Roles'
        run: |
         az acr repository list --name dotnetaksdemo --output table
         az role assignment list --assignee '${{ secrets.AZURE_CLIENT_ID }}'
         echo "Role AcrPull Assignment"
         az role assignment create --assignee '${{ secrets.AZURE_CLIENT_ID }}' --role acrpull --scope /subscriptions/21820b91-3cd2-4b83-a038-2545bf88960c/resourceGroups/azureRG/providers/Microsoft.ContainerRegistry/registries/dotnetaksdemo
         sleep 60
         echo "Roles After Assignment"
         az role assignment list --scope /subscriptions/21820b91-3cd2-4b83-a038-2545bf88960c/resourceGroups/azureRG/providers/Microsoft.ContainerRegistry/registries/dotnetaksdemo
  # --assignee '${{ secrets.AZURE_CLIENT_ID }}'
      - name: 'Create AKS Cluster'
        run: |
         echo "Create AKS"
         if az aks show --resource-group azureRG --name myAKSCluster > /dev/null 2>&1; then
          echo "Cluster myAKSCluster already exists. Skipping creation."
          az aks update --name myAKSCluster --resource-group AzureRG --attach-acr dotnetaksdemo --assign-identity d8330a3a-eb52-43ed-9cf9-b73bc19f1325 --assign-kubelet-identity /subscriptions/21820b91-3cd2-4b83-a038-2545bf88960c/resourcegroups/AzureRG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/myKubeletIdentity

         else
         echo "Cluster myAKSCluster does not exist. Creating AKS cluster..."
         az aks create --resource-group AzureRG --name myAKSCluster --node-count 1 --node-vm-size Standard_B4ps_v2 --generate-ssh-keys          
         az aks update --name myAKSCluster --resource-group AzureRG --attach-acr dotnetaksdemo --assign-identity d8330a3a-eb52-43ed-9cf9-b73bc19f1325 --assign-kubelet-identity /subscriptions/21820b91-3cd2-4b83-a038-2545bf88960c/resourcegroups/AzureRG/providers/Microsoft.ManagedIdentity/userAssignedIdentities/myKubeletIdentity
         fi
         echo "Show AKS principalID"
         az aks show --resource-group azureRG --name myAKSCluster  -o table 
       
      - name: 'Connect to cluster using kubectl'
        run: |
         az aks get-credentials --resource-group azureRG --name myAKSCluster
      - name: 'Get Nodes of Cluster & pods' 
        run: |
         kubectl get nodes
         kubectl apply -f ./pod.yaml
         kubectl get pods -o wide
         kubectl describe pod my-pod
  #kubectl get Deployments
         
